### ISSUE TITLE
Put a LICENSE information in this repository.

### ISSUE THREAD

**Issue by phantomcraft** [mykola2312/blowfish#1]
I want to reuse the code of this repository but I don't know its license.

A license information in this repository would be useful.

**Comment by mykola2312** [comment]
It's free (free as in freedom) and open source

**Comment by mykola2312** [comment]
It's free (free as in freedom) and open source

**Comment by phantomcraft** [comment]
I don't want to rewrite a Blowfish implementation because there are dozens around web, but most of them, including these on Github, are licensed under MIT or GPL. I also found your reference implementation of Blowfish the most perfect among the others.

It's ok, as I can see is placed on Public Domain, so I will reuse.
